language: csharp
solution: alipay-sdk-net.sln
mono: none
dotnet: 2.1.502

script:
  - dotnet restore
  - cd AlipaySDKNet.Standard && dotnet build && cd ..
  - cd UnitTestNetCore && dotnet build && cd ..
  - dotnet test UnitTestNetCore /p:AltCover=true

after_success:
  - cd UnitTestNetCore
  - bash <(curl -s https://codecov.io/bash) -c -F unittests
  